#!/bin/sh
'''exec' "/Users/mayanktyagi/Desktop/Whitehat/Projects/Project 118/PRO-C118-Project-Boilerplate-main/myvenv/bin/python3" "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from markdown.__main__ import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
